#!/bin/bash

usage()
{
cat << EOF

  scanduplicate <base_path> <target_path>

  example:

      $  scanduplicate essential/usr domE/usr
EOF
}

scandir()
{
# Search each entry in base_path, delete same file in target_path.
for entry in $(ls $1 -A); do
    if [ -e "$2/${entry}" ] || [ -L "$2/${entry}" ]; then
        if [ -d "$2/${entry}" ] && [ ! -L "$2/${entry}" ] && \
            [ -d "$1/${entry}" ] && [ ! -L "$1/${entry}" ]; then
            # Only enter dir when both $1/entry & $2/entry are directory
            scandir "$1/$entry" "$2/$entry"
        elif [ -f "$2/${entry}" ] && [ -f "$1/${entry}" ]; then
            # Delete when both $1/entry & $2/entry are regular file
            rm "$2/${entry}"
        elif [ -L "$2/${entry}" ] && [ -L "$1/${entry}" ]; then
            # Delete when both $1/entry & $2/entry are sympol-link
            rm "$2/${entry}"
        fi
        # Ignore other conditions
    fi
done;
# Remove empty diretory in target_path
if [ $(ls -Al "$2"|wc -l) -eq 1 ]; then
    rmdir "$2"
fi
}

if [ -z "$2" ]; then
    usage
    exit
fi

scandir $1 $2
