#!/bin/bash

# ensure we get expected and consistent modes for dir creation, etc..
umask 0022

if [ "$CUBE_DEBUG_SET_X_IF_SET" = 1 ] ; then
    set -x
fi

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.

CURRENTDIR=$(pwd)
BASEDIR=$(readlink -f $(dirname $BASH_SOURCE))
IMAGESDIR="${BASEDIR}/../images"
CONTAINERSDIR="${BASEDIR}/../images/containers"
PACKAGESDIR="${BASEDIR}/../packages"
SBINDIR="${BASEDIR}/../sbin"
LIBDIR="${BASEDIR}/../lib"
export SBINDIR
if [ -z "${CONFIG_DIRS}" ] ; then
    CONFIG_DIRS="${BASEDIR}/../config $HOME/.overc/"
fi
export CONFIG_DIRS

# Debug Levels - fixed values
DEBUG_SILENT=0
DEBUG_CRIT=1
DEBUG_WARN=2
DEBUG_INFO=4
DEBUG_VERBOSE=7

FACTORY_SNAPSHOT=".factory"

# Set your default debug level
: ${DEBUG_DEFAULT:=${DEBUG_INFO}}
: ${FUNCTIONS_FILE="$SBINDIR/functions.sh"}

# Dynamic debug level
DEBUG_LEVEL=${DEBUG_DEFAULT}
: ${TRACE:=0}

#get the target's architecture, x86 or not x86?
export X86_ARCH=true
if [ $(uname -p 2>/dev/null | grep -ic x86) != '1' ]; then
    # if the processor type isn't x86, set x86 to false
    export X86_ARCH=false

    # but! some emulated platforms (i.e. qemu) report unknown, so we 
    # double check, and set ourselves back to x86 if unkown is reported
    if [ $(uname -p 2>/dev/null | grep -ic unknown) = '1' ]; then
	export X86_ARCH=true
    fi
fi

## Load function file(s)
if ! [ -e $FUNCTIONS_FILE ]; then
    debugmsg ${DEBUG_CRIT} "[ERROR]: Could not find function definitions (${FUNCTIONS_FILE})"
    exit 1
fi
source $FUNCTIONS_FILE

usage()
{
cat << EOF

  cubeit-installer <base image> <device>

    -b: use btrfs
    -i or --interactive: use the interactive configuration interface
    --finaldev: boot from this block dev. Default is vda
    --ttyconsoledev: set dev used for tty console
    --ttyconsolecn: set container name for providing agetty
    --privilegedcn: set container name for privileged
    --encrypt: encrypt the rootfs
    --encrypt-data: encrypt the data
    --ima-sign: sign the files with IMA signature
    --yes: answer 'yes' to all questions for clearing TPM and wiping
           the rootfs device for the disk encryption

EOF
}

if [ -z "$1" ]; then
    usage
    exit
fi

btrfs=0
ttyconsolecn=""
ttyconsoledev="ttyS0"
do_encryption=0
do_data_encryption=0
do_ima_sign=0
no_interaction=0
while [ $# -gt 0 ]; do
    case "$1" in
    --config) 
            CONFIG_FILES="${CONFIG_FILES} $2"
	    shift
            ;;
    --image)
            IMAGE="$2"
	    shift
            ;;
    --artifacts)
            ARTIFACTS_DIR="$2"
	    shift
            ;;
    -v) verbose=t
            ;;
    -b) btrfs=1
            ;;
    --yes) no_interaction=1
            ;;
	--interactive|-i)
		# Interactive config mode
		INTERACTIVE_MODE=1
		for app in blockdev dialog; do
			verify_utility $app || { echo >&2 "ERROR: $app is not available"; exit 1; }
		done
		;;
    --finaldev) final_dev="$2"
            shift
            ;;
    --ttyconsoledev) ttyconsoledev="$2"
            shift
            ;;
    --ttyconsolecn) ttyconsolecn="$2"
            shift
            ;;
    --privilegedcn) privilegedcn="$2"
            shift
            ;;
    --partition_layout)
            FDISK_PARTITION_LAYOUT_INPUT="$2"
            shift
            ;;
    --encrypt)
            do_encryption=1
	    ;;
    --encrypt-data)
            do_data_encryption=1
            ;;
    --ima-sign)
            do_ima_sign=1
            ;;
         *) break
            ;;
    esac
    shift
done

if [ -z "${CONFIG_FILES}" ]; then
    CONFIG_FILES="config-installer.sh"
fi

if [ $no_interaction -eq 0 ] && [ -v CONFIRM_INSTALL ] && [ ${CONFIRM_INSTALL} -eq 0 ]; then
    no_interaction=1
fi

colon_separated_config_dirs=`echo ${CONFIG_DIRS} | sed 's/ /:/g'`
for config in ${CONFIG_FILES}; do
    config_to_source="${config}"

    # check to see if the config exists. If it doesn't search the config paths
    if ! [ -e "${config}" ]; then
	for d in ${CONFIG_DIRS}; do
	    if [ -e "${d}/${config}" ]; then
		config_to_source="${d}/${config}"
	    fi
	done

	if [ -z "${config_to_source}" ]; then
	    echo "ERROR: Could not find configuration file (${config_to_soure})."
	    echo "Try using an absolute path or the file must be in one of ($(echo ${CONFIG_DIRS} | tr ' ' ','))."
	    exit 1
	fi
    fi
    export PATH="$PATH:${colon_separated_config_dirs}:$( dirname $config_to_source )"
    source `basename ${config_to_source}`
done

OLDIFS=$IFS
IFS='
'
#source the board specific functions
if [ -e $SBINDIR/functions-${BOARD_NAME}.sh ]; then
    debugmsg ${DEBUG_CRIT} "[INFO]: load board ${BOARD_NAME} specific functions"
    source $SBINDIR/functions-${BOARD_NAME}.sh
fi

#source any local function definitions
if [ -e "${LOCAL_POST_FUNCTION_DEFS}" ] ; then
    source ${LOCAL_POST_FUNCTION_DEFS}
fi

IFS=$OLDIFS

## typical qemu disk is vdb
rootfs=$1
raw_dev=$2

if [ -e "$rootfs" ]; then
    rootfs=`readlink -f $rootfs`
else
    if [ ! -f "${IMAGESDIR}/$rootfs" ]; then
	debugmsg ${DEBUG_CRIT} "[ERROR]: install rootfs ($rootfs) not found"
	exit 1
    fi
    rootfs="${IMAGESDIR}/$rootfs"
fi

# remove /dev/ if specified
raw_dev="`echo ${raw_dev} | sed 's|/dev/||'`"

# Check if interactive mode will be used
if [ -n "$INTERACTIVE_MODE" ] && [ "$INTERACTIVE_MODE" -eq 1 ]; then
	if [ -z "$ARTIFACTS_DIR" ] || [ ! -d "$ARTIFACTS_DIR" ]; then
		ARTIFACTS_DIR=$IMAGESDIR
	fi
	debugmsg ${DEBUG_INFO} "Entering interactive mode..."
	SAVE_CONFIG_FOLDER="saved_config"
	recursive_mkdir ${SAVE_CONFIG_FOLDER}
	tmpconf="${SAVE_CONFIG_FOLDER}/config.sh"
	echo "" > ${tmpconf}
	promptsdir=${LIBDIR}/prompts
	INSTALL_TYPE=full
	for f in `ls $promptsdir`; do
		source $promptsdir/$f
		basename=${f%.*}
		${basename:5}
		if [ $? -ne 0 ]; then
			debugmsg ${DEBUG_CRIT} -e "\n\n\nFailed to generate config using interactive mode, run again or specify a config via --config option."
			exit 1
		fi
	done

	debugmsg ${DEBUG_INFO} -e "\n\n\nUser config saved. Installation will continue."
	debugmsg ${DEBUG_INFO} "You can specify --config ${SAVE_CONFIG_FOLDER}/config.sh option in your later installations to use the exact same configurations."
	CONFIG_FILES="`pwd`/${SAVE_CONFIG_FOLDER}/config.sh"
	source $CONFIG_FILES
fi

if [ ! -d "${IMAGESDIR}" ]; then
    if [ -n "${ARTIFACTS_DIR}" ]; then
	IMAGESDIR=${ARTIFACTS_DIR}
    else
	debugmsg ${DEBUG_CRIT} "[ERROR]: images dir (${IMAGESDIR}) not found"
	exit 1
    fi
fi

if ! [ -n "$DISTRIBUTION" ]; then
    DISTRIBUTION="OverC"
fi

if [ -v CONTAINER_PREFIX -a -n "$CONTAINER_PREFIX" ] ; then
    export CNAME_PREFIX="--prefix $CONTAINER_PREFIX"
fi

if [ $do_encryption -eq 1 ] ; then
    which luks-setup.sh >/dev/null 2>&1
    if [ $? -eq 1 ]; then
        echo "WARNING: --encrypt ignored due to missing luks-setup.sh. \
Install cryptfs-tpm2"
        do_encryption=0
    fi

    which cryptsetup >/dev/null 2>&1
    if [ $? -eq 1 ]; then
        echo "WARNING: --encrypt ignored due to missing cryptsetup. \
Install cryptsetup"
        do_encryption=0
    fi
fi

get_container_name_by_prop()
{
    local prop=$1
    local ret=""

    for i in "${!container_map[@]}"; do
	#echo "key  : $i"
	#echo "value: ${container_map[$i]}"
	echo ${container_map[$i]} | grep -qw $prop
	if [ $? -eq 0 ]; then
	    ret="${i}"
	fi
    done

    echo "${ret}"
}

get_prop_value_by_container()
{
    local cn=$1
    local prop=$2
    local ret=""

    props=${container_map[$cn]}
    for k in $props; do
        ret=`echo $k | grep "${prop}=" | sed "s/$prop=//g"`
        if [ -n "$ret" ]; then
            break
        fi 
    done

    echo "${ret}"
}

get_prop_isset_by_container()
{
    local cn=$1
    local prop=$2
    local ret=""

    props=${container_map[$cn]}
    for k in $props; do
        echo $k | grep -q "${prop}"
        if [ $? = 0 ]; then
	    ret=1
            break
        fi
    done

    echo "${ret}"
}

ima_sign()
{
    local root_dir="$1"
    local mnt_dirs="`grep $root_dir /proc/mounts | awk '{ print $2 }'`"

    for dir in `ls $root_dir`; do
        local dst_dir="$root_dir/$dir"
	local skip_signing=0

        for _dir in $mnt_dirs; do
            # skip root directory
            [ "$_dir" = "$root_dir" ] && continue

            local fs_type="`grep $_dir /proc/mounts | awk '{ print $3 }'`"

            if [ "$dst_dir" = "$_dir" ]; then
                if [ $fs_type != "btrfs" -a $fs_type != "ext4" ]; then
                    skip_signing=1
                    break
                fi
            fi
        done

        [ $skip_signing -eq 1 ] && continue

        evmctl ima_sign --hashalgo sha256 --rsa -r -t f "$dst_dir" && {
            debugmsg ${DEBUG_INFO} "[INFO]: IMA signing completed for $dst_dir."
        } || {
            debugmsg ${DEBUG_INFO} "[ERROR]: IMA signing occurs with error for $dst_dir."
            exit 1
        }
    done
}

# containers are listed in HDINSTALL_CONTAINERS as:
#    <full path>/<container tgz>:<properties>
declare -g -A container_map=()
containers_to_check=${HDINSTALL_CONTAINERS}
if [ -n "$containers_to_check" ]; then
    create_property_map container_map ${HDINSTALL_CONTAINERS}
else
    # if there's a valid containers directory, we'll install everything
    # found there. Otherwise, we'll use HDINSTALL_CONTAINERS
    if [ -d "${CONTAINERSDIR}" ]; then
	for c in $(ls ${CONTAINERSDIR} | grep '\-dom0\-' ; ls ${CONTAINERSDIR} | grep -v '\-dom0\-' ); do
	    HDINSTALL_CONTAINERS="$HDINSTALL_CONTAINERS `readlink -f ${CONTAINERSDIR}/$c`"
	done
    fi
    create_property_map container_map ${HDINSTALL_CONTAINERS}
fi


# if ttyconsolecn wasn't passed on the command line, check to see
# if a container in the configuration had the "console" property. If
# so, set it. Otherwise, assign cube-desktop as the default
if [ -z "${ttyconsolecn}" ]; then
    ttyconsolecn=`get_container_name_by_prop console`
    if [ -z "${ttyconsolecn}" ]; then
	ttyconsolecn="cube-desktop"
    fi
fi

if [ -z "${privilegedcn}" ]; then
    privilegedcn=`get_container_name_by_prop privileged`
    if [ -z "${privilegedcn}" ]; then
        privilegedcn="cube-desktop"
    fi
fi

# create partitions
# 
#  1: boot
#  2: swap
#  3: root
#  4. lxc

BOOTLABEL="${BOOTLABEL=OVERCBOOT}"
SWAPLABEL="${SWAPLABEL=SWAP}"
ROOTLABEL="${ROOTLABEL=OVERCROOTFS}"
LXCLABEL="${LXCLABEL=OVERCCN}"

PARTITIONTYPE=""
USE_GPT=0

if test ! $(which fdisk); then
	debugmsg ${DEBUG_CRIT} "[ERROR]: Unable to find 'fdisk'."
	debugmsg ${DEBUG_CRIT} "[ERROR]: Please ensure fdisk is installed and in your PATH."
	exit 1
fi
# Get supported fdisk command line options
avail_fdisk_options=$(fdisk -h | grep "^\ *-" | cut -d',' -f1 | xargs)


if [ -n "${FDISK_PARTITION_LAYOUT_INPUT}" ]; then
        FDISK_PARTITION_LAYOUT="${FDISK_PARTITION_LAYOUT_INPUT}"
elif [ -z "${FDISK_PARTITION_LAYOUT}" ]; then
        FDISK_PARTITION_LAYOUT="${SBINDIR}/fdisk-4-partition-layout.txt"
        # This fdisk-4-partition-layout.txt file only suitable to mbr partition type,
        # but not all fdisk versions support -t. So we test and assign if it is available

	# If fdisk supports the '-t' disklabel option use it. Determine which variant to
	# use, prefer to use 'mbr' when available (though currently the same as 'dos')
	if [[ $avail_fdisk_options == *"-t"* ]]; then
		if $(fdisk -t mbr 2>&1 | grep -q unsupported); then
			PARTITIONTYPE="-t dos"
		else
			PARTITIONTYPE="-t mbr"
		fi
	fi
fi

if [ "${PARTITIONTYPE_OVERRIDE}" != "" ] ; then
    PARTITIONTYPE="$PARTITIONTYPE_OVERRIDE"
    echo ${PARTITIONTYPE} | grep -q gpt
    if [ $? = 0 ] ; then
	USE_GPT=1
    fi
fi

debugmsg ${DEBUG_INFO} "[INFO]: creating partitions using (${FDISK_PARTITION_LAYOUT})"
debugmsg ${DEBUG_INFO} "          1) boot"
if [ "$SWAPLABEL" != "NOSWAP" ] ; then
	debugmsg ${DEBUG_INFO} "          2) swap"
fi
debugmsg ${DEBUG_INFO} "          3) root"
debugmsg ${DEBUG_INFO} "          4) container (lxc)"
# We partition the raw device as passed to the script. This is
# nuke and pave .. so be careful!
if [ $USE_GPT -eq 1 ] ; then
    parted -s /dev/${raw_dev} print 2> /dev/null |grep ^Part |grep -q gpt
    if [ $? -ne 0 ] ; then
	parted -s /dev/${raw_dev} mklabel gpt
    fi
fi
if [ -f ${FDISK_PARTITION_LAYOUT} ]; then
        fdisk ${PARTITIONTYPE} /dev/${raw_dev} < ${FDISK_PARTITION_LAYOUT} >/dev/null 2>&1
else
        debugmsg ${DEBUG_CRIT} "[ERROR]: Could not find the fdisk partitions file ${FDISK_PARTITION_LAYOUT}"
        exit 1
fi
# For filesystem creation, we need the partitions. But some devices
# name them differently than a hard disk (i.e mmcblk or nbd) and 
# have 'p' in the partion names. In that case, we need to create a
# separate device with the 'p' and then use it for filesystem 
# creation.
fs_dev=${raw_dev}
if [ $(echo $raw_dev | grep -c 'mmcblk') ==  "1" ]; then
       fs_dev="${raw_dev}p"
fi
if [ $(echo $raw_dev | grep -c 'nbd') ==  "1" ]; then
       loop_device=t
       fs_dev="${raw_dev}p"
fi
if [ $(echo $raw_dev | grep -c 'loop') ==  "1" ]; then
       loop_device=t
       fs_dev="${raw_dev}p"
       partprobe /dev/${raw_dev}
fi

if [ "$SWAPLABEL" != "NOSWAP" ] ; then
	## create filesystems
	debugmsg ${DEBUG_INFO} "[INFO]: creating filesystems"
	debugmsg ${DEBUG_INFO} "[INFO]: creating swap"
	mkswap -L $SWAPLABEL /dev/${fs_dev}2
	if [ $USE_GPT -eq 1 ] ; then
	    parted -s /dev/${raw_dev} name 2 $SWAPLABEL
	fi
fi

set -e
debugmsg ${DEBUG_INFO} "[INFO]: creating /boot (vfat)"
mkfs.vfat -I -n $BOOTLABEL /dev/${fs_dev}1

if [ $USE_GPT -eq 1 ] ; then
    parted -s /dev/${raw_dev} name 1 $BOOTLABEL
fi

## define the device file names for rootfs and lxc filesystem
rootfs_dev=${fs_dev}3
lxc_fs_dev=${fs_dev}4

if [ $USE_GPT -eq 1 ] ; then
    parted -s /dev/${raw_dev} name 3 $ROOTLABEL
    parted -s /dev/${raw_dev} name 4 $LXCLABEL
fi

if [ $do_encryption -eq 1 ]; then
    ## Evict all objects for the first creation.
    cmd="luks-setup.sh -f -e -d /dev/${rootfs_dev} -n ${ROOTLABEL}_encrypted >/dev/null 2>&1"
    [ $no_interaction -eq 1 ] && cmd="echo Y | $cmd"
    eval "$cmd"
    rootfs_dev="mapper/${ROOTLABEL}_encrypted"
fi

if [ $do_data_encryption -eq 1 ]; then
    ## Encrypt data drive
    cmd="luks-setup.sh -f -d /dev/${lxc_fs_dev} -n ${LXCLABEL}_encrypted" >/dev/null 2>&1
    [ $no_interaction -eq 1 ] && cmd="echo Y | $cmd"
    eval "$cmd"
    lxc_fs_dev="mapper/${LXCLABEL}_encrypted"
fi

if [ $btrfs -eq 0 ]; then
    debugmsg ${DEBUG_INFO} "[INFO]: creating / (ext4)"
    mkfs.ext4 -v -L $ROOTLABEL /dev/${rootfs_dev}
    mkfs.ext4 -v -L $LXCLABEL /dev/${lxc_fs_dev}
else
    debugmsg ${DEBUG_INFO} "[INFO]: creating / (btrfs)"
    set +e
    has_f=`mkfs.btrfs 2>&1 |grep -q '^.*\-f' && echo -f`
    set -e
    mkfs.btrfs $has_f -L $ROOTLABEL /dev/${rootfs_dev}
    mkfs.btrfs $has_f -L $LXCLABEL /dev/${lxc_fs_dev}
fi
set +e

if [ -z "${TMPMNT}" ]; then
    TMPMNT=`mktemp -d /tmp/pulsarmountXXXXX`
    export TMPMNT
fi
mkdir -p ${TMPMNT}
mount /dev/${rootfs_dev} ${TMPMNT}

if [ $btrfs -eq 0 ]; then
	mkdir ${TMPMNT}/boot

	cd ${TMPMNT}
else
	# create a subvolume
	btrfs subvolume create ${TMPMNT}/rootfs

	mkdir ${TMPMNT}/rootfs/boot

	cd ${TMPMNT}/rootfs
fi

## vfat filesystem doesn't support soft link, here umount boot partition and
## then copy kernel image to boot partition

# we are either in ${TMPMNT} or ${TMPMNT}/rootfs
debugmsg ${DEBUG_INFO} "[INFO]: installing rootfs ($rootfs)"
tar --warning=no-timestamp --numeric-owner -xpf $rootfs

# sanity check whether the private key is available for IMA signing
if [ $do_ima_sign -eq 1 ]; then
    if [ ! -f etc/keys/privkey_evm.pem ]; then
        if [ -z "${IMA_PRIVKEY}" -o ! -f "${IMA_PRIVKEY}" ]; then
            debugmsg ${DEBUG_WARN} "[WARNING]: IMA signing disabled"
            do_ima_sign=0
        fi
    fi
fi

mount /dev/${fs_dev}1 mnt

## Process kernel into /boot
bundled_kernel=0
if [ -e "${INSTALL_KERNEL}" ] ; then
	inst_img=${INSTALL_KERNEL##*}
	if [ "${inst_img/uImage/}" != "$inst_img" ] ; then
		inst_kernel=uImage
	else
		inst_kernel=bzImage
	fi
	cp ${INSTALL_KERNEL} mnt/${inst_kernel}
	cp ${INSTALL_KERNEL} mnt/${inst_kernel}_bakup
elif ls boot/uImage-* >/dev/null 2>&1; then
	cp boot/uImage-* mnt/uImage
	#create a backup kernel for recovery boot
	cp boot/uImage-* mnt/uImage_bakup
elif ls boot/bzImage-* >/dev/null 2>&1; then
	if ls boot/bzImage-initramfs-* >/dev/null 2>&1; then
	    bundled_kernel=1
	fi
	cp boot/bzImage-* mnt/bzImage
	#create a backup kernel for recovery boot
	cp boot/bzImage-* mnt/bzImage_bakup
elif ls boot/fitImage-* >/dev/null 2>&1; then
	cp boot/fitImage-* mnt/fitImage
	#create a backup kernel for recovery boot
	cp boot/fitImage-* mnt/fitImage_bakup
fi
 
## Process initrd into /boot
img=`ls boot/*Image-* 2> /dev/null`
# First use the config file specified one, if not set,
# then find it in ${IMAGESDIR}
# create both a initrd-<version> and initrd
if [ -e "$INSTALL_INITRAMFS" ]; then
	cp $INSTALL_INITRAMFS mnt/initrd
elif [ -n "$img" ] ; then
	debugmsg ${DEBUG_INFO} "[INFO]: installing initramfs ($INSTALL_INITRAMFS)"
	kernel=`basename boot/*Image-*`
	kernel_version=`echo $kernel | sed 's/^[^0-9]*-//g'`
	initrd="initrd-${kernel_version}.gz"

	#Generally in deploy/image dir, there will be several initramfs files
	#with different name, but they are the same file, so here just copy one
	#of them is ok.
	for i in $( ls ${IMAGESDIR}/*-initramfs-*.cpio.gz ); do
		cp /$i mnt/initrd
		break
	done
fi

if [ $bundled_kernel -eq 1 -a $do_ima_sign -eq 1 ]; then
	[ -n "${IMA_POLICY}" -a -f "${IMA_POLICY}" ] &&
	    debugmsg ${DEBUG_WARN} "[WARNING]: Skip to deploy ${IMA_POLICY}"

	[ -n "${IMA_PUBKEY}" -a -f "${IMA_PUBKEY}" ] && {
	    debugmsg ${DEBUG_WARN} "[WARNING]: Skip to deploy ${IMA_PUBKEY}"
	    # Don't copy the public key to rootfs.
	    IMA_PUBKEY=""

	    # If the external public key cannot be deployed due to using
	    # the bundled kernel, labelling filesystems becomes meaningless.
	    [ -n "${IMA_PRIVKEY}" -a -f "${IMA_PRIVKEY}" ] && {
	        # No private key available for IMA signing.
		if [ ! -f etc/keys/privkey_evm.pem ]; then
		    debugmsg ${DEBUG_WARN} "[WARNING]: IMA signing disabled due to using the bundled kernel"
		    do_ima_sign=0
		else
		    IMA_PRIVKEY=""
		fi
	    }
	}
fi

# repack initramfs as required
if [ $do_ima_sign -eq 1 -a -f mnt/initrd ]; then
	if [ -n "${IMA_POLICY}" -a -f "${IMA_POLICY}" ]; then
	    copy_ima_policy=1
	else
	    copy_ima_policy=0
	fi

	if [ -n "${IMA_PUBKEY}" -a -f "${IMA_PUBKEY}" ]; then
	    copy_ima_pubkey=1
	else
	    copy_ima_pubkey=0
	fi

	if [ $copy_ima_policy -eq 1 -o $copy_ima_pubkey -eq 1 ]; then
	    topdir="`pwd`"
	    initrd_src="$topdir/mnt/initrd"

	    mkdir -p /tmp/initramfs-repack
	    cd /tmp/initramfs-repack

	    zcat $initrd_src | cpio -id

	    [ $copy_ima_policy -eq 1 ] && {
		cp -f "${IMA_POLICY}" etc/ima_policy && {
		    debugmsg ${DEBUG_INFO} "IMA policy copied"
		} || {
		    debugmsg ${DEBUG_INFO} "[ERROR] Unable to copy IMA policy"
		    exit 1
		}
	    }

	    [ $copy_ima_pubkey -eq 1 ] && {
		cp -f "${IMA_PUBKEY}" etc/keys/pubkey_evm.pem && {
		    debugmsg ${DEBUG_INFO} "IMA public key copied"
		} || {
		    debugmsg ${DEBUG_INFO} "[ERROR] Unable to copy IMA public key"
		    exit 1
		}
	    }

	    find . | cpio -o -H newc > "$initrd_src"
	    cd -
	    cp -f "$initrd_src" "mnt/${initrd}"
	    rm -rf /tmp/initramfs-repack
	fi
fi

## Deploy kernel modules to overwrite what was there if INSTALL_MODULES is set
if [ -n "${INSTALL_MODULES}" ]; then
	debugmsg ${DEBUG_INFO} "[INFO]: installing kernel modules (${INSTALL_MODULES##*/})"
	tar --numeric-owner -xpf ${INSTALL_MODULES}
fi

if [ $btrfs -eq 1 ]; then
	# get the subvolume id of /mnt/rootfs using:
	subvol=`btrfs subvolume list ${TMPMNT} | awk '{print $2;}'`
	# set default volume when mounted
	btrfs subvolume set-default $subvol ${TMPMNT}/rootfs

	cd /
	sync
	umount ${TMPMNT}/rootfs/mnt
	umount ${TMPMNT}/
	mount -o subvolid=${subvol} /dev/${rootfs_dev} ${TMPMNT}
	mount /dev/${fs_dev}1 ${TMPMNT}/mnt
	cd ${TMPMNT}/
fi

# A fixup for virtual installs. If we've booted off a usb device
# our device will be 'vdb', but since qemu can't re-order bootable
# devices, vdb goes away when a reboot happens and you want to boot
# the install. In that case, vdb becomes vda. So we switch it below
# here to avoid fixups during first boot.
if [ -z ${final_dev} ]; then
    final_dev=${raw_dev}
    if [ "${raw_dev}" = "vdb" ]; then
	final_dev="vda"
    fi
fi

if ${X86_ARCH}; then
    debugmsg ${DEBUG_INFO} "[INFO]: installing grub"

    chroot ${TMPMNT} /bin/bash -c "mount -t devtmpfs none /dev"
    chroot ${TMPMNT} /bin/bash -c "mount -t proc none /proc"

    if [ -n "$loop_device" ]; then
	chroot ${TMPMNT} /bin/bash -c "grub-install --boot-directory=/mnt --modules=\" boot linux ext2 fat serial part_msdos part_gpt normal iso9660 search\" /dev/${raw_dev}"
    else
	chroot ${TMPMNT} /bin/bash -c "grub-install --boot-directory=/mnt --force /dev/${raw_dev}"
    fi

    mkdir -p ${TMPMNT}/mnt/grub
    cat <<EOF >${TMPMNT}/mnt/grub/grub.cfg
set default="0"

serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1
terminal_input console serial
terminal_output console serial
set timeout=5

menuentry "$DISTRIBUTION" {
	insmod gzio
	insmod ext2
	insmod fat
	search --no-floppy --label $BOOTLABEL --set=root
	echo	'Loading Linux ...'
	linux	/bzImage root=LABEL=$ROOTLABEL ro rootwait $GRUB_KERNEL_PARAMS
	echo	'Loading initial ramdisk ...'
	initrd	/initrd
}

menuentry "$DISTRIBUTION recovery" {
        insmod gzio
        insmod ext2
        insmod fat
        search --no-floppy --label $BOOTLABEL --set=root
        echo    'Loading Linux ...'
        linux   /bzImage_bakup root=LABEL=$ROOTLABEL rootflags=subvol=rootfs_bakup ro rootwait $GRUB_RECOVERY_KERNEL_PARAMS
        echo    'Loading initial ramdisk ...'
        initrd  /initrd
}

EOF

    # Don't allow to load the detached initramfs if the bundled kernel used.
    [ $bundled_kernel -eq 1 ] &&
        sed -i '/^\s*initrd\s\+/d' ${TMPMNT}/mnt/grub/grub.cfg

    # If IMA appraisal is enabled but the filesystems are not labelled, a
    # boot failure will occur.
    if [ $do_ima_sign -eq 0 ]; then
        sed -i 's/^\s*linux .*/& ima_appraise=off/' ${TMPMNT}/mnt/grub/grub.cfg
    elif [ $do_encryption -eq 0 ]; then
        sed -i 's/^\s*linux .*/& ima_policy=tcb/' ${TMPMNT}/mnt/grub/grub.cfg
    fi

    debugmsg ${DEBUG_INFO} "[INFO]: grub installed"
    
    # fixups for virtual installs
    if [ "${raw_dev}" = "vdb" ]; then
	sed -i "s/${raw_dev}/${final_dev}/" ${TMPMNT}/boot/grub/grub.cfg
    fi

    if [ -f boot/efi/EFI/BOOT/boot*.efi ]; then
	debugmsg ${DEBUG_INFO} "[INFO]: installing EFI artifacts"
	mkdir -p mnt/EFI/BOOT
	cp -a boot/efi/EFI mnt

	if [ -n "${INSTALL_GRUBEFI_CFG}" -a -f "${INSTALL_GRUBEFI_CFG}" ]; then
	    cp "${INSTALL_GRUBEFI_CFG}" mnt/EFI/BOOT/grub.cfg
	else
	    cat <<EOF >mnt/EFI/BOOT/grub.cfg
set default="0"
set timeout=3
set color_normal='light-gray/black'
set color_highlight='light-green/blue'

insmod efivar
get_efivar -f uint8 -s SECURE_OFF SetupMode

if [ "\${SECURE_OFF}" = "1" ]; then
    set timeout=0

    menuentry "Automatic Certificate Provision" {
        chainloader \${prefix}/LockDown.efi
    }
fi

menuentry "$DISTRIBUTION" {
    set fallback=1
    chainloader /bzImage root=LABEL=$ROOTLABEL ro rootwait initrd=/initrd
}

menuentry "$DISTRIBUTION recovery" {
    chainloader /bzImage_bakup root=LABEL=$ROOTLABEL rootflags=subvol=rootfs_bakup ro rootwait initrd=/initrd
}
EOF
	fi

	echo `basename mnt/EFI/BOOT/boot*.efi` >mnt/startup.nsh
	chmod +x mnt/startup.nsh

	# Don't allow to load the detached initramfs if the bundled kernel used.
	[ $bundled_kernel -eq 1 ] &&
	    sed -i 's/\(^\s*chainloader\s\+.*bzImage.*\)\s\+initrd=[^[:space:]]*\(.*\)/\1\2/g' mnt/EFI/BOOT/grub.cfg

	# If IMA appraisal is enabled but the filesystems are not labelled, a
	# boot failure will occur.
	if [ $do_ima_sign -eq 0 ]; then
	    sed -i 's/^\s*chainloader\s\+.*bzImage.*/& ima_appraise=off/' mnt/EFI/BOOT/grub.cfg
	elif [ $do_encryption -eq 0 ]; then
            sed -i 's/^\s*chainloader\s\+.*bzImage.*/& ima_policy=tcb/' mnt/EFI/BOOT/grub.cfg
        fi
    else
	install -m 0755 ${SBINDIR}/startup.nsh mnt/
	sed -i "s/%ROOTLABEL%/${ROOTLABEL}/" mnt/startup.nsh
	sed -i "s/%INITRD%/${initrd}/" mnt/startup.nsh
	sed -i "s/%BZIMAGE%/bzImage/" mnt/startup.nsh
    fi
else # arm architecture
    if [ -e "${INSTALL_DTB}" ]; then
        install_dtb "./mnt" "${INSTALL_DTB}"
    elif [ -e "${IMAGESDIR}/dtb" ]; then
        install_dtb "./mnt" "${IMAGESDIR}/dtb"
    fi
    if [ -e "${INSTALL_BOOTLOADER}" ]; then
        if [ -e "${INSTALL_BOOTLOADER_ENV}" ]; then
	    install_bootloader "${raw_dev}" "./mnt" ${INSTALL_BOOTLOADER} "${BOARD_NAME}" ${INSTALL_BOOTLOADER_ENV}
        else
	    install_bootloader "${raw_dev}" "./mnt" ${INSTALL_BOOTLOADER} "${BOARD_NAME}"
	fi
    elif [ -e ${IMAGESDIR}/*_boot.bin ]; then
	BOARD_NAME=`basename ${IMAGESDIR}/*_boot.bin | sed 's/_boot\.bin//'`
	install_bootloader "${raw_dev}" "./mnt" "${IMAGESDIR}/${BOARD_NAME}_boot.bin" "${BOARD_NAME}"
    fi
fi

#Remove the systemd's costly remount of the root partition from /etc/fstab,
#and also remove API filesystems mounting from it, as systemd will mount them itself.
#sed -i '\/dev\/root/d' ${TMPMNT}/etc/fstab
sed -i '/^proc/d' ${TMPMNT}/etc/fstab
sed -i '/^devpts/d' ${TMPMNT}/etc/fstab
sed -i '/^tmpfs/d' ${TMPMNT}/etc/fstab
sed -i '/^usbdevfs/d' ${TMPMNT}/etc/fstab
# If using IMA it should /sys/kernel/security is mounted by the container manager
sed -i '/^securityfs/d' ${TMPMNT}/etc/fstab

if [ "$SWAPLABEL" != "NOSWAP" ] ; then
	echo "LABEL=$SWAPLABEL none swap sw 0 0" >> ${TMPMNT}/etc/fstab
fi

[ $do_ima_sign -eq 1 ] && mount_opts="defaults,iversion" || mount_opts="defaults"
echo "LABEL=$BOOTLABEL /boot auto $mount_opts 0 0" >> ${TMPMNT}/etc/fstab
echo "LABEL=$LXCLABEL /var/lib/lxc auto $mount_opts 0 0" >> ${TMPMNT}/etc/fstab

if [ -e "$INSTALL_SMARTCONFIG" ]; then
	cp $INSTALL_SMARTCONFIG ${TMPMNT}/var/lib/smart/config
elif [ -e /${IMAGESDIR}/config.smart ]; then
	cp /${IMAGESDIR}/config.smart ${TMPMNT}/var/lib/smart/config
fi

#make essential system use vty 1 to login and disable the autoVTs of systemd
sed -i "s/#NAutoVTs=.*$/NAutoVTs=0/g" ${TMPMNT}/etc/systemd/logind.conf
sed -i "s/#ReserveVT=.*$/ReserveVT=0/g" ${TMPMNT}/etc/systemd/logind.conf
gettys=$( ls ${TMPMNT}/etc/systemd/system/getty.target.wants/getty* )
for k in ${gettys}; do
	ln -s -f /dev/null ${k}
done
ln -sf /lib/systemd/system/getty@.service ${TMPMNT}/etc/systemd/system/getty.target.wants/getty@tty1.service

# Disable all not needed services in essentail
if [ -n "${SERVICE_DISABLE_ESSENTIAL}" ]; then
    for s in ${SERVICE_DISABLE_ESSENTIAL}; do
        service_disable ${s}
    done
fi

if [ -n "${HDINSTALL_CONTAINERS}" ]; then
    subvol=""
    debugmsg ${DEBUG_INFO} "[INFO]: installing containers"
    if [ ! -d ${TMPMNT}/var/lib/lxc ]; then
        mkdir -p ${TMPMNT}/var/lib/lxc
    fi
    mount /dev/${lxc_fs_dev} ${TMPMNT}/var/lib/lxc

    mkdir -p ${TMPMNT}/tmp

    if [ $btrfs -eq 1 ]; then
        #create a subvolume for container images
        btrfs subvolume create ${TMPMNT}/var/lib/lxc/workdir
        subvol=`btrfs subvolume list ${TMPMNT}/var/lib/lxc | awk '{print $2;}'`
        sync
        umount ${TMPMNT}/var/lib/lxc
        mount -o subvol=workdir /dev/${lxc_fs_dev} ${TMPMNT}/var/lib/lxc
    fi

    # deal with static IPs and the "Networking Prime"
    network_offsets=()
    network_container=()

    # Lookahead to see if a network prime is defined. We need to do this to
    # determine if we need tell overc-cctl to use bridged networking or not.
    overc_cctl_bridged_net_opt=" -b "
    for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
	cname=`${SBINDIR}/cubename $CNAME_PREFIX $c`
	net_offset=`get_prop_value_by_container $cname "net"`
	if [ -n "$net_offset" ] && [ $net_offset -eq 1 ]; then
	    overc_cctl_bridged_net_opt=" "
	    break;
	fi
    done


    CNRECORD=`mktemp /tmp/hdcontainerXXXXX`
    export CNRECORD

    for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
	cname=`${SBINDIR}/cubename $CNAME_PREFIX $c`
	# Just save a record in tmp file
	mergepath=`get_prop_value_by_container $cname "mergepath"`

	echo "$cname::$mergepath" >> ${CNRECORD}
    done;

    for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
	debugmsg ${DEBUG_INFO} "[INFO]: installing $c"

	# containers names are "prefix-<container name>-<... suffixes >
	container_src=`basename $c`
	cname=`${SBINDIR}/cubename $CNAME_PREFIX $c`
	cp $c ${TMPMNT}/tmp/
	cp ${SBINDIR}/overc-cctl ${TMPMNT}/tmp/
	
	# Any container that has a console attribute gets a virtual console
	consoleattr=`get_prop_isset_by_container $cname "console"`
	# hardconsole means a container gets the physical console device
	hardconsoleattr=`get_prop_isset_by_container $cname "hardconsole"`

	ttyconsole_opt="-S ${ttyconsoledev}"
	if [ "${ttyconsolecn}" == "${cname}" -o -n "$consoleattr" ]; then
            ttyconsole_opt="-s ${ttyconsole_opt}"
	fi
	
	if [ "${privilegedcn}" == "${cname}" ]; then
	    ttyconsole_opt=" -P ${ttyconsole_opt}"
	fi

	if [ -n "${hardconsoleattr}" ]; then
	    ttyconsole_opt="-T ${ttyconsole_opt}"
	fi

	# vty attributes are: <number>,<properites>
	# properties: active or <empty>
	vty_num=`get_prop_value_by_container $cname "vty"`
	if [ -n "$vty_num" ]; then
	    attribute1=`echo $vty_num | cut -f1 -d,`
	    attribute2=`echo $vty_num | cut -f2 -d,`
	    if [ "$attribute1" != "$attribute2" ]; then
		# they are different, so ther's a number,<attribute>
		vty_num="${attribute1}"
		vty_prop="${attribute2}"
		if [ "${vty_prop}" == "active" ]; then
		    foreground_container="${cname}"
		    foreground_vty="${vty_num}"
		fi
	    fi

	    ttyconsole_opt=" -v $vty_num ${ttyconsole_opt}"
	fi

	# If a net offset is specified for this container add
	# it to the network_offsets list in the overc_config_vars.yml
	# in order to have ansible configure the container.
	# An offset of '1' will make that container the
	# "network prime".
	net_offset=`get_prop_value_by_container $cname "net"`
	if [ -n "$net_offset" ]; then
	    if [ $net_offset -eq 1 ]; then
		network_prime="$cname"
	    else
		network_offsets+=("'$net_offset'")
		network_container+=("'$cname'")
	    fi
	fi

	# if subuid property is specified for this container,
	# this container is going to be unprivileged.
	subuid=`get_prop_value_by_container $cname "subuid"`
	subuid_opt=""
	if [ -n "${subuid}" ]; then
		subuid_opt="-u ${subuid}"
		echo "root:${subuid}:65536" >> ${TMPMNT}/etc/subuid
		echo "root:${subuid}:65536" >> ${TMPMNT}/etc/subgid
	fi

	# actually install the container
	export LXCBASE="${TMPMNT}/var/lib/lxc"
	export BINDMNTBASE="${TMPMNT}/opt/container"
	export HOSTDIR="${TMPMNT}"
	case $container_src in
	    *-dom0-*)
		monitor_container_opt=""
		monitored_container=`get_container_name_by_prop monitored`
		if [ -n "${monitored_container}" ]; then
			monitor_container_opt="-m ${monitored_container}"
		fi

		## TODO. make overc-cctl into smaller commands that manipulate the containers
		##       on a more granular basis.
		##       like: extract, configure, add service, etc.
		${SBINDIR}/overc-cctl add -d -a -c -g onboot -t 0 -n $cname -f $c ${ttyconsole_opt} ${monitor_container_opt} ${overc_cctl_bridged_net_opt}
		;;
	    *-dom1-*)
		${SBINDIR}/overc-cctl add -d -p -c -g peer -t 0 -n $cname -f $c ${ttyconsole_opt} ${overc_cctl_bridged_net_opt}
		;;
	    *)
		${SBINDIR}/overc-cctl add ${subuid_opt} -d -p -c -g peer -t 0 -n $cname -f $c ${ttyconsole_opt} ${overc_cctl_bridged_net_opt}
		;;
	esac

	if [ -e "$INSTALL_SMARTCONFIG" ]; then
	    cp $INSTALL_SMARTCONFIG ${TMPMNT}/var/lib/lxc/$cname/rootfs/var/lib/smart/config
	elif [ -e /${IMAGESDIR}/config.smart ]; then
	    cp /${IMAGESDIR}/config.smart ${TMPMNT}/var/lib/lxc/$cname/rootfs/var/lib/smart/config
	fi

	rm ${TMPMNT}/tmp/$(basename $c)
    done

    #cleanup temp files
    rm ${CNRECORD}

    # install and modify services
    for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
	container_src=`basename $c`
	cname=`${SBINDIR}/cubename $CNAME_PREFIX $c`

	# if there was a foreground container defined (attribute 'active' on a vty), then we
	# install a chvt service to make sure it is in the foreground after boot. Note, this
	# currently does not touch essential, but could in the future.
	if [ -n "${foreground_container}" ]; then
	    service_install chvt.service ${cname}
	    service_modify "%OVERC_ACTIVE_VT%" ${foreground_vty} ${cname} chvt.service
	fi

        # Disable all not needed services in dom0
        if [ -n "${SERVICE_DISABLE_DOM0}" -a "${cname}" = "dom0" ]; then
            for s in ${SERVICE_DISABLE_DOM0}; do
                service_disable ${s} ${cname}
            done
        fi

        # Disable or add condition checking for all not needed services in container
        if [ -n "${SERVICE_DISABLE_CONTAINER}" ]; then
            for s in ${SERVICE_DISABLE_CONTAINER}; do
                service_disable ${s} ${cname}
            done
        fi

        if [ -n "${SERVICE_CONDITION_CONTAINER}" ]; then
            for s in ${SERVICE_CONDITION_CONTAINER}; do
                service_add_condition_for_container ${s} ${cname}
            done
        fi
    done

    # Setup networking prime and static IPs, unless using bridged networking
    if [ ! -v network_prime ]; then
	# Fallback to using bridged networking (see overc_bridge_networking DISTRO_FEATURE)
	sed -i "s/^configure_network_prime/#configure_network_prime/"  \
	    ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml
	debugmsg ${DEBUG_INFO} "[INFO]: Using bridged networking."
    else
	if [ ! -v NETWORK_DEVICE ]; then
	    NETWORK_DEVICE=""
	fi
	if [ ! -v NETWORK_DEVICE_CLASSES ]; then
	    NETWORK_DEVICE_CLASSES=""
	fi
	pathtocontainer=${TMPMNT}/var/lib/lxc/${network_prime}
	if [ -e "${pathtocontainer}/config" ]; then
	    # Pass the network device through to the designated network prime container
	    if [ ! -z "${NETWORK_DEVICE_CLASSES}" ]; then
	    	for i in ${NETWORK_DEVICE_CLASSES}; do
	    	     echo "lxc.network.type = phys" >> ${pathtocontainer}/config
	             echo "lxc.network.link = $i" >> ${pathtocontainer}/config
	        done
	    fi

	    # Enable configuring the network prime container by ansible on first boot
	    sed -i "s/^\(network_prime_container:\).*$/\1 ${network_prime}/" \
		${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml

	    # Set the network prime device for network prime container by ansible on first boot
	    if [ ! -z "${NETWORK_DEVICE}" ]; then
                sed -i "s/^\(network_device:\).*$/\1 ${NETWORK_DEVICE}/" \
		    ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml
	    else
                sed -i "s/^network_device/#network_device/"  \
	            ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml
	    fi

	    # Specify any network offsets for containers with static IPs
	    if [ -v network_offsets ] && [ ${#network_offsets[@]} -gt 0 ]; then
		network_offsets=$(IFS=,; echo "${network_offsets[*]}")
		network_container=$(IFS=,; echo "${network_container[*]}")

		sed -i "s/^\(cname\: \).*\]$/\1 \[$network_container\]/" \
		    ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml

		sed -i "s/^\(coffset\: \).*\]$/\1 \[$network_offsets\]/" \
		    ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml
	    fi

	    debugmsg ${DEBUG_INFO} "[INFO]: Set ${network_prime} as the network prime."
	else
	    debugmsg ${DEBUG_WARN} "[WARNING]: Invalid network prime defined."
	fi
    fi

    # setup timezone if it is configured
    if [ ! -z "${TIMEZONE}" ]; then
	debugmsg ${DEBUG_INFO} "[INFO]: Set ${TIMEZONE} as the timezone."
	echo "timezone: ${TIMEZONE}" >> ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml
    fi

    # setup initial user if it is configured
    if [ ! -z "${INITIAL_USER}" ]; then
	debugmsg ${DEBUG_INFO} "[INFO]: Set initial user."
	sed -i "s/^\(initial_user:\).*$/\1 ${INITIAL_USER}/" \
	    ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml
	echo "initial_passwd: `cat $CONFIG_FILES | grep INITIAL_PASSWD | cut -f 2 -d=`" \
	    >> ${TMPMNT}/etc/overc-conf/ansible/overc_config_vars.yml
    fi

    if [ -n "${LOCAL_CUSTOM_HDD_POST_FUNCS}" ]; then
	for f in ${LOCAL_CUSTOM_HDD_POST_FUNCS}; do
	    ${f}
	done
    fi

    [ $do_ima_sign -eq 1 ] &&
        ima_sign "${TMPMNT}/var/lib/lxc"

    sync
    umount ${TMPMNT}/var/lib/lxc

    if [ $btrfs -eq 1 ]; then
        if [ -z "$subvol" ]; then
            debugmsg ${DEBUG_WARN} "[WARNING]: Could not get subvolume id, thus cannot create factory reset snapshot"
        else
            mount /dev/${lxc_fs_dev} ${TMPMNT}/var/lib/lxc
            btrfs subvolume set-default $subvol ${TMPMNT}/var/lib/lxc
            btrfs subvolume snapshot ${TMPMNT}/var/lib/lxc/workdir ${TMPMNT}/var/lib/lxc/${FACTORY_SNAPSHOT}
            #snapshot subvolume recursively
            subvolumes="$(btrfs subvolume list -c ${TMPMNT}/var/lib/lxc/workdir | awk '{print $NF}')"
            for subvolume in $subvolumes; do
                snapshot_directory="${TMPMNT}/var/lib/lxc/${FACTORY_SNAPSHOT}/${subvolume}"
                if [ -d "${snapshot_directory}" ]; then
                    rm -rf "${snapshot_directory}"
                    btrfs subvolume snapshot "${TMPMNT}/var/lib/lxc/workdir/${subvolume}" "${TMPMNT}/var/lib/lxc/${FACTORY_SNAPSHOT}/$(dirname ${subvolume})"
                fi
            done
            sync
            umount ${TMPMNT}/var/lib/lxc
        fi
    fi
fi

if [ -d "${PACKAGESDIR}" ]; then
    debugmsg ${DEBUG_INFO} "[INFO]: Copying packages to installation as /opt/packages"
    mkdir -p opt/
    cp -r ${PACKAGESDIR} opt/

    chroot . /bin/bash -c "\\
smart channel -y --add all type=rpm-md baseurl=file://opt/packages/rpm/all/; \\
smart channel -y --add core2_64 type=rpm-md baseurl=file://opt/packages/rpm/core2_64/; \\
smart channel -y --add genericx86_64 type=rpm-md baseurl=file://opt/packages/rpm/genericx86_64; \\
smart channel -y --add lib32_x86 type=rpm-md baseurl=file://opt/packages/rpm/lib32_x86/; \\
smart update"

fi

if [ $do_ima_sign -eq 1 ]; then
    [ ! -d ${TMPMNT}/etc/keys ] && mkdir -p ${TMPMNT}/etc/keys

    [ -n "${IMA_PUBKEY}" -a -f "${IMA_PUBKEY}" ] &&
        cp -f "${IMA_PUBKEY}" "${TMPMNT}/etc/keys/pubkey_evm.pem"

    ima_sign "${TMPMNT}"
fi

debugmsg ${DEBUG_INFO} "[INFO]: performing cleanup"
# cleanup
cd /
sync
umount ${TMPMNT}/mnt

cat /proc/mounts | grep -q "${TMPMNT}/dev"
if [ $? -eq 0 ]; then
	umount ${TMPMNT}/dev
fi
cat /proc/mounts | grep -q "${TMPMNT}/proc"
if [ $? -eq 0 ]; then
	umount ${TMPMNT}/proc
fi

umount ${TMPMNT}
if [ $? -ne 0 ]; then
    echo ERROR: umount ${TMPMNT} failed
    exit 1
fi

#create a backup snapshot for rootfs
if [ $btrfs -eq 0 ]; then
	:
else
	debugmsg ${DEBUG_INFO} "[INFO]: Creating a snapshot of rootfs for recovery."
	#mount the root subvolume
	mount -o subvolid=5 /dev/${rootfs_dev} ${TMPMNT}
	if [ -e "${TMPMNT}/rootfs" ]; then
		btrfs subvolume snapshot ${TMPMNT}/rootfs ${TMPMNT}/rootfs_bakup
		btrfs subvolume snapshot ${TMPMNT}/rootfs ${TMPMNT}/${FACTORY_SNAPSHOT}
	fi
	sync
	umount ${TMPMNT}
	if [ $? -ne 0 ]; then 
	    echo ERROR: umount ${TMPMNT} failed
	    exit             
	fi
fi

rmdir ${TMPMNT}

if [ $do_encryption -eq 1 ]; then
    echo "INFO: Closing LUKS ..."

    cryptsetup luksClose "${ROOTLABEL}_encrypted"
fi
if [ $do_data_encryption -eq 1 ]; then
    cryptsetup luksClose "${LXCLABEL}_encrypted"
fi

# don't run this on a host!!
# sync ; sync ; echo 3> /proc/sys/vm/drop_caches
# echo o > /proc/sysrq-trigger
